### ISSUE TITLE
Making a usage of DCC.Store, creating Two source of truths (one for overview and one for detail plots)

### ISSUE THREAD

**Issue by Pfanfel** [Pfanfel/davi_us_energy#4]
Once a value in the overview gets changed, a new copy for the detail plots is made.

Using dcc.store API to store the information to from the filtering -> Storage is output of filtering

-> The only input of the plots will be the storage

Overview state perstits the state, so the user can come back even if selections were made in the detail charts

https://dash.plotly.com/sharing-data-between-callbacks

**Comment by michalinajnk** [comment]
**_CONSUMPTION STORAGE:_**

1. dcc.Store for consumption for an overview --> initialized within the declaration
2. dcc.Store for consumption for the detailed overview (small graphs) --> initialized with the callback for overview plots. The current-state of the 'dcc.Store for consumption for an overview' is copied to this component. It is updated on the use interaction with the small, detailed graphs.

_**PRODUCTION STORAGE:**_

1. dcc.Store for production for an overview --> initialize on the callback of selected variables on the production overview (On BooleanSwitch) 
2. dcc.Store for production for the detailed overview (small graphs)
>  --> initialize on the callback of selected variables on the production overview (On BooleanSwitch )

**Comment by michalinajnk** [comment]
To do:

- [ ] Create 4 dcc Store components
- [ ] Create callbacks to filter the storage as the OutputStorage, Input:  TimeSlider, Map, Icicle chosen categories etc.
1. >  callback to filter consumption overview data
2. >  callback to filter consumption detailed data
3. >  callback to filter production overview data
4. >  callback to filter production detailed data
- [ ] callbacks for each graph component and as the Input take a storage
